import {
  ProcessTypeArr,
  TextProcessProps,
} from '../types';

const TYPE: ProcessTypeArr = ['shadow', 'ellipsis'];

const DEFAULT_PROPS: TextProcessProps = {
  text: '',
  reRenderDependentProperties: ['text'],
  type: 'shadow',
  className: '',
  style: {},
  buttonClassName: '',
  buttonStyle: {},
  onClick: null,
  isClickOriginalEvent: false,
  getIsFold: null,
  isDefaultFold: true,
  unfoldButtonText: 'Show Less',
  foldButtonText: 'Show All',
  isShowAllContent: false,
  isMustButton: false,
  isMustNoButton: false,
  lineHeight: 24,
  isRenderShowAllDOM: false,
  /** >>>>>>仅ellipsis配置 */
  ellipsisLineClamp: 2,
  isJsComputed: false,
  fontSize: 12,
  fontClassName: '',
  fontStyle: {},
  textEndSlot: null,
  extraOccupiedW: 0,
  buttonBeforeSlot: null,
  /** >>>>>>仅shadow配置 */
  shadowInitBoxShowH: 76,
  shadowButtonPlacement: 'outer',
  isShadowLayer: true,
  shadowClassName: '',
  shadowStyle: {},
};

const JS_COMPUTED_VALID_CSS_PROPERTIES = [
  'font-size',
  'font-weight',
  'font-style',
  'font-family',
  'font-feature-settings',
  'font-kerning',
  'font-language-override',
  'font-optical-sizing',
  'font-stretch',
  'font-size-adjust',
  // 'font-smooth',
  'font-synthesis',
  'font-variant',
  'font-variant-alternates',
  'font-variant-caps',
  'font-variant-east-asian',
  'font-variant-emoji',
  'font-variant-ligatures',
  'font-variant-numeric',
  'font-variant-position',
  'font-variation-settings',
  'initial-letter',
  'inline-size',
  'line-height',
  'line-height-step',
  // 'line-break',
  'letter-spacing',
  // 'text-shadow',
  'text-transform',
  'text-indent',
  'text-combine-upright',
  'text-emphasis',
  'text-emphasis-position',
  'text-emphasis-style',
  'text-orientation',
  'text-rendering',
  'text-size-adjust',
  // 'vertical-align',
  // 'white-space',
  'word-spacing',
  // 'word-break',
  // 'word-wrap',
  // 'writing-mode',
];

const JS_COMPUTED_NUMBER_TO_PX_PROPERTIES = [
  'font-size',
  'letter-spacing',
  'word-spacing',
  'text-indent',
  'line-height-step',
  'inline-size',
];

export {
  TYPE,
  DEFAULT_PROPS,
  JS_COMPUTED_VALID_CSS_PROPERTIES,
  JS_COMPUTED_NUMBER_TO_PX_PROPERTIES,
};
